<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<Version>1.0.0</Version>
	</PropertyGroup>

	<ItemDefinitionGroup>
		<Reference Private="False"/>
	</ItemDefinitionGroup>

	<ItemGroup>
		<Reference Include="FrooxEngine.Weaver" HintPath="$(ResonitePath)FrooxEngine.Weaver.dll" />
		<Reference Include="Mono.Cecil" HintPath="$(ResonitePath)Mono.Cecil.dll" />
	</ItemGroup>

</Project>
